# Generated by Django 2.0.7 on 2018-07-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(default=0, help_text="node's depth.")),
                ('temperature', models.FloatField(default=15.0, help_text="the water's temperature.")),
                ('address', models.TextField(help_text='other message.', max_length=250)),
                ('date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='NodeIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(help_text='IP address,e.g. 1.1.1.1', max_length=15)),
                ('Mask', models.CharField(help_text='Mask,e.g. 255.255.255.0', max_length=15)),
                ('Mac', models.CharField(help_text='Mac address,e.g. 00-00-00-00-00-01', max_length=17)),
                ('info', models.TextField(help_text='the message of this node collect!', max_length=500)),
                ('nodeaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodeapp.NodeAddress')),
            ],
        ),
    ]
