# Generated by Django 2.0.7 on 2018-08-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0002_auto_20180731_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeaddress',
            name='address',
            field=models.TextField(help_text='where is the node?', max_length=250),
        ),
    ]
