# Generated by Django 2.0.7 on 2018-08-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0003_auto_20180820_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collected_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(default=0, help_text="node's depth.")),
                ('temperature', models.FloatField(default=15.0, help_text="the water's temperature.")),
                ('address', models.TextField(help_text='where is the node?', max_length=250)),
                ('date', models.DateField(verbose_name='date published')),
                ('info', models.TextField(help_text='the message of this node collect!', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of administrator', max_length=20)),
                ('job', models.CharField(help_text='job', max_length=50)),
                ('call', models.CharField(help_text='the phone number', max_length=11)),
                ('email', models.EmailField(help_text='the email of manager', max_length=50)),
                ('office_address', models.CharField(help_text='office address', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Net_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, help_text='the number of node.')),
                ('IP', models.GenericIPAddressField(help_text='IP address,e.g. 1.1.1.1', protocol='IPv4')),
                ('Mask', models.GenericIPAddressField(help_text='Mask,e.g. 255.255.255.0', protocol='IPv4')),
                ('Mac', models.CharField(help_text='Mac address,e.g. 00-00-00-00-00-01', max_length=17)),
                ('collected_info', models.ManyToManyField(help_text='Select a address for this nodeIp', to='nodeapp.Collected_Info')),
            ],
        ),
        migrations.RemoveField(
            model_name='nodeip',
            name='nodeaddress',
        ),
        migrations.DeleteModel(
            name='NodeAddress',
        ),
        migrations.DeleteModel(
            name='NodeIP',
        ),
    ]
