# Generated by Django 2.0.7 on 2018-08-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0004_auto_20180824_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected_info',
            name='depth',
            field=models.FloatField(default=0, help_text="node's depth(零下几米)."),
        ),
    ]
