# Generated by Django 2.0.7 on 2018-08-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0005_auto_20180824_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected_info',
            name='temperature',
            field=models.FloatField(default=15.0, help_text="the water's temperature.(摄氏度)"),
        ),
    ]
