# Generated by Django 2.0.7 on 2018-08-27 04:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('nodeapp', '0006_auto_20180824_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collected_Info',
            new_name='CollectedInfo',
        ),
        migrations.RenameModel(
            old_name='Net_Node',
            new_name='NetNode',
        ),
        migrations.RenameField(
            model_name='netnode',
            old_name='collected_info',
            new_name='collectedinfo',
        ),
    ]
