# Generated by Django 2.0.7 on 2018-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0007_auto_20180827_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunProtocols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocols', models.CharField(help_text='the protocol which the node will use for simulating.', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='netnode',
            name='collectedinfo',
        ),
        migrations.AddField(
            model_name='collectedinfo',
            name='netnode',
            field=models.ManyToManyField(help_text='一个信息可能对应多个节点，一个节点产生多个信息', to='nodeapp.NetNode'),
        ),
        migrations.AlterField(
            model_name='collectedinfo',
            name='info',
            field=models.TextField(help_text='the message of this node collect!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='netnode',
            name='IP',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='IP address,e.g. 1.1.1.1', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='netnode',
            name='Mac',
            field=models.CharField(default='00-00-00-00-00-00', help_text='Mac address,e.g. 00-00-00-00-00-01', max_length=17),
        ),
        migrations.AlterField(
            model_name='netnode',
            name='Mask',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='Mask,e.g. 255.255.255.0', protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='runprotocols',
            name='netnode',
            field=models.ManyToManyField(help_text='一种协议可以用于多个节点仿真。', to='nodeapp.NetNode'),
        ),
    ]
