# Generated by Django 2.0.7 on 2018-10-07 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0008_auto_20180918_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationParament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumNode', models.IntegerField(help_text='The number of Nodes')),
                ('Modulation', models.CharField(help_text='Modulation,QPSK,MFSK', max_length=10)),
                ('MACPtorocols', models.CharField(help_text='for example,aloha protocol', max_length=50)),
                ('Route', models.CharField(help_text='route protocols', max_length=50)),
                ('Transport', models.CharField(help_text='for instance,UDP', max_length=50)),
                ('Simulation', models.CharField(help_text='simulation or emulation', max_length=50)),
                ('TestName', models.CharField(help_text='the name of test', max_length=100)),
                ('RunningTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='仿真开始时间')),
                ('PacketLoss', models.IntegerField(default=0, help_text='PacketLoss，丢包率')),
                ('Delay', models.IntegerField(default=0, help_text='delay ,延时')),
                ('AverageThroughput', models.IntegerField(default=0, help_text='AverageThroughput,平均吞吐量')),
            ],
            options={
                'ordering': ['RunningTime'],
            },
        ),
        migrations.RemoveField(
            model_name='collectedinfo',
            name='netnode',
        ),
        migrations.RemoveField(
            model_name='runprotocols',
            name='netnode',
        ),
        migrations.DeleteModel(
            name='CollectedInfo',
        ),
        migrations.DeleteModel(
            name='NetNode',
        ),
        migrations.DeleteModel(
            name='RunProtocols',
        ),
    ]
