# Generated by Django 2.0.7 on 2018-10-08 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodeapp', '0009_auto_20181007_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparament',
            name='SimulationUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='AverageThroughput',
            field=models.IntegerField(default=-1, help_text='AverageThroughput,平均吞吐量'),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='Delay',
            field=models.IntegerField(default=-1, help_text='delay ,延时'),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='PacketLoss',
            field=models.IntegerField(default=-1, help_text='PacketLoss，丢包率'),
        ),
    ]
