# Generated by Django 2.0.7 on 2018-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0010_auto_20181008_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparament',
            name='Application',
            field=models.CharField(default='CBR', help_text='应用层协议,for instance,CBR', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='MACPtorocols',
            field=models.CharField(help_text='MAC层协议,for example,aloha protocol', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='Modulation',
            field=models.CharField(help_text='调制方式，Modulation,QPSK,MFSK', max_length=10),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='NumNode',
            field=models.IntegerField(help_text='仿真节点数量，The number of Nodes'),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='Route',
            field=models.CharField(help_text='路由协议,route protocols', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='Simulation',
            field=models.CharField(help_text='硬件仿真还是软件仿真,simulation or emulation', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulationparament',
            name='Transport',
            field=models.CharField(help_text='传输层协议,for instance,UDP', max_length=50),
        ),
    ]
