# Generated by Django 2.1.3 on 2018-11-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0011_auto_20181008_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparament',
            name='RecvNodeMac',
            field=models.CharField(default='', help_text='接收消息节点的物理地址', max_length=18),
        ),
        migrations.AddField(
            model_name='simulationparament',
            name='SendNodeMac',
            field=models.CharField(default='', help_text='发送消息的节点物理地址', max_length=18),
        ),
    ]
