# Generated by Django 2.1.3 on 2018-11-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0012_auto_20181107_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationparament',
            name='NumNode',
        ),
    ]
