# Generated by Django 2.1.7 on 2019-04-24 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0014_auto_20190330_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_Location', models.CharField(help_text='geographical location', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MAC_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_MAC_Address', models.CharField(default='', help_text='节点的物理地址', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='MSG_PH_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_PH', models.DecimalField(decimal_places=1, default=7.0, help_text='PH value, such as 7.00，12.01', max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MSG_Press_Attrubute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_Press', models.DecimalField(decimal_places=2, default=101.01, help_text='water pressure, such as 101.01 KPa', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MSG_Temperature_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_Temperature', models.DecimalField(decimal_places=1, default=20.0, help_text='Temperature , such as 37.0 centidegree', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Net_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_IPv4', models.GenericIPAddressField(help_text='Node IPv4 address')),
            ],
        ),
        migrations.CreateModel(
            name='Node_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_ID', models.IntegerField(help_text='Node ID')),
                ('Node_Geo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.Geography_Attribute')),
                ('Node_MAC', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nodeapp.MAC_Attribute')),
                ('Node_Net', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.Net_Attribute')),
                ('Node_PH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_PH_Attribute')),
                ('Node_PS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_Press_Attrubute')),
                ('Node_TP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_Temperature_Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collect_Time', models.DateTimeField(default=django.utils.timezone.now, help_text='某一时刻上的节点')),
                ('Collect_Node', models.ManyToManyField(null=True, to='nodeapp.Node_Attribute')),
            ],
        ),
    ]
