# Generated by Django 2.1.7 on 2019-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0015_geography_attribute_mac_attribute_msg_ph_attribute_msg_press_attrubute_msg_temperature_attribute_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_node',
            name='Collect_Node',
            field=models.ManyToManyField(help_text='worker Node', to='nodeapp.Node_Attribute'),
        ),
    ]
