# Generated by Django 2.1.7 on 2019-04-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0017_auto_20190424_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simultaion_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loss_Packet', models.DecimalField(decimal_places=2, default=0.0, help_text='loss packet', max_digits=3)),
                ('Delay_Time', models.IntegerField(default=0, help_text='Millisecond')),
            ],
        ),
        migrations.AddField(
            model_name='time_node',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'sleep'), ('a', 'active'), ('p', 'poweroff ')], default='s', help_text='time node status,default status is sleep', max_length=1),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_Geo',
            field=models.ForeignKey(help_text='Geographical location,可能是个非具体位置', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.Geography_Attribute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_ID',
            field=models.IntegerField(default=0, help_text='Node ID', verbose_name='节点序号'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_MAC',
            field=models.OneToOneField(help_text='MAC address', on_delete=django.db.models.deletion.CASCADE, to='nodeapp.MAC_Attribute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_Net',
            field=models.ForeignKey(help_text='IPv4 Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.Net_Attribute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_PH',
            field=models.ForeignKey(help_text='PH value', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_PH_Attribute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_PS',
            field=models.ForeignKey(help_text='Pressure,(KPa)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_Press_Attrubute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_TP',
            field=models.ForeignKey(help_text='temperature,(centidegree) ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_Temperature_Attribute'),
        ),
    ]
