# Generated by Django 2.1.7 on 2019-04-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0018_auto_20190428_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_PH',
            field=models.ForeignKey(blank=True, help_text='PH value', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_PH_Attribute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_PS',
            field=models.ForeignKey(blank=True, help_text='Pressure,(KPa)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_Press_Attrubute'),
        ),
        migrations.AlterField(
            model_name='node_attribute',
            name='Node_TP',
            field=models.ForeignKey(blank=True, help_text='temperature,(centidegree) ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.MSG_Temperature_Attribute'),
        ),
        migrations.AlterField(
            model_name='time_node',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'Sleep'), ('r', 'Running'), ('p', 'Poweroff ')], default='s', help_text='time node status,default status is sleep', max_length=1),
        ),
    ]
