# Generated by Django 2.1.7 on 2019-04-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0019_auto_20190428_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emulation_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Name', models.CharField(help_text='test name', max_length=100)),
                ('Emul_Time', models.DateTimeField(auto_now=True, help_text='仿真时间')),
                ('Recv_File', models.FileField(blank=True, help_text='Receive File', upload_to='')),
                ('Send_File', models.FileField(blank=True, help_text='Send File', upload_to='')),
                ('Recv_Node', models.ForeignKey(help_text='Recv Node', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.Node_Attribute')),
            ],
        ),
    ]
