# Generated by Django 2.1.7 on 2019-04-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0020_emulation_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulation_test',
            name='Send_Node',
            field=models.ForeignKey(help_text='Send Node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Send', to='nodeapp.Node_Attribute'),
        ),
        migrations.AlterField(
            model_name='emulation_test',
            name='Recv_Node',
            field=models.ForeignKey(help_text='Recv Node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Recv', to='nodeapp.Node_Attribute'),
        ),
    ]
