# Generated by Django 2.1.7 on 2019-05-06 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0022_auto_20190506_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_attribute',
            name='Node_Geo',
        ),
        migrations.RemoveField(
            model_name='node_attribute',
            name='Node_Net',
        ),
        migrations.RemoveField(
            model_name='node_attribute',
            name='Node_PH',
        ),
        migrations.RemoveField(
            model_name='node_attribute',
            name='Node_PS',
        ),
        migrations.RemoveField(
            model_name='node_attribute',
            name='Node_TP',
        ),
        migrations.AlterField(
            model_name='emulation_test',
            name='Recv_Node',
            field=models.ForeignKey(help_text='Recv Node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Recv', to='nodeapp.Raw_Node'),
        ),
        migrations.AlterField(
            model_name='emulation_test',
            name='Send_Node',
            field=models.ForeignKey(help_text='Send Node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Send', to='nodeapp.Raw_Node'),
        ),
        migrations.AlterField(
            model_name='time_node',
            name='Note_Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 9, 50, 46, 109290, tzinfo=utc), help_text='记录时间'),
        ),
        migrations.DeleteModel(
            name='Node_Attribute',
        ),
    ]
