# Generated by Django 2.1.7 on 2019-05-06 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0023_auto_20190506_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_node',
            name='Note_Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 10, 0, 30, 587051, tzinfo=utc), help_text='记录时间'),
        ),
    ]
