# Generated by Django 2.1.7 on 2019-05-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodeapp', '0026_auto_20190506_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSG_Time', models.DateTimeField(auto_now=True, help_text='留言时间')),
                ('LeavingMSG', models.CharField(help_text='leaving message', max_length=250)),
                ('Commenter', models.ForeignKey(blank=True, help_text='only registered user can user ite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='the title of this topic', max_length=30)),
                ('Content', models.CharField(help_text='talk about', max_length=250)),
                ('Spoke_Time', models.DateTimeField(auto_now=True, help_text='话题发起时间')),
                ('Good', models.IntegerField(default=0, help_text='点赞数量')),
                ('Reviewer_MSG', models.ForeignKey(blank=True, help_text='留言', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodeapp.Message_Board')),
                ('Spoke_Man', models.ForeignKey(blank=True, help_text='only registered user can user ite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Spoke_Man', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
