# Generated by Django 2.1.7 on 2019-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0029_auto_20190511_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Reviewer_MSG',
            field=models.ManyToManyField(default=None, help_text='留言', to='nodeapp.Message_Board'),
        ),
    ]
