# Generated by Django 3.0.4 on 2020-04-14 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodeapp', '0030_auto_20190511_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='UanEmulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.CharField(help_text='the id of emulation task', max_length=48)),
                ('srcFilePath', models.CharField(help_text='the srcFilePath', max_length=255)),
                ('emuFilesPath', models.CharField(help_text='the emulated files ', max_length=255)),
                ('emuTime', models.DateTimeField(auto_now=True, help_text='the emulated time')),
            ],
        ),
        migrations.AlterField(
            model_name='raw_node',
            name='Geo_Address',
            field=models.CharField(default='', help_text='node geography address', max_length=255),
        ),
        migrations.DeleteModel(
            name='Geography_Attribute',
        ),
        migrations.AddField(
            model_name='uanemulation',
            name='emuNodeIDs',
            field=models.ManyToManyField(help_text='emulated IDs', to='nodeapp.Raw_Node'),
        ),
        migrations.AddField(
            model_name='uanemulation',
            name='emuUser',
            field=models.ForeignKey(blank=True, help_text='registered user can use', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emuUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uanemulation',
            name='srcNodeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='srcNodeId', to='nodeapp.Raw_Node'),
        ),
    ]
