# Generated by Django 3.0.4 on 2020-04-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0031_auto_20200414_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uanemulation',
            name='emuNodeIDs',
        ),
    ]
