# Generated by Django 2.0.7 on 2020-09-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0032_remove_uanemulation_emunodeids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship_msg',
            fields=[
                ('Ship_ID', models.IntegerField(help_text='节点逻辑序号,从1开始计数', primary_key=True, serialize=False)),
                ('poi_lat', models.DecimalField(decimal_places=7, default=39.1621281, help_text='维度信息:例: 23.1621281', max_digits=9)),
                ('poi_lng', models.DecimalField(decimal_places=7, default=39.1621281, help_text='维度信息:例: 113.3529971', max_digits=10)),
            ],
        ),
    ]
