# Generated by Django 2.0.7 on 2020-09-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0033_ship_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_msg',
            name='Ship_ID',
            field=models.IntegerField(default=1, help_text='节点逻辑序号,从1开始计数', primary_key=True, serialize=False),
        ),
    ]
