# Generated by Django 2.0.7 on 2020-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0034_auto_20200901_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_msg',
            name='other',
            field=models.CharField(default='lmx', help_text=' other', max_length=255),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='poi_lng',
            field=models.DecimalField(decimal_places=7, default=113.3529971, help_text='维度信息:例: 113.3529971', max_digits=10),
        ),
    ]
