# Generated by Django 2.0.7 on 2020-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0035_auto_20200901_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_msg',
            name='other',
            field=models.CharField(default='其他信息', help_text=' other', max_length=255),
        ),
    ]
