# Generated by Django 2.0.7 on 2020-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0036_auto_20200901_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_msg',
            name='heading',
            field=models.FloatField(blank=True, help_text='偏航角', null=True),
        ),
    ]
