# Generated by Django 2.0.7 on 2020-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0037_ship_msg_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_msg',
            name='poi_lat',
            field=models.FloatField(blank=True, help_text='维度信息:例: 23.1621281', null=True),
        ),
    ]
