# Generated by Django 2.0.7 on 2020-12-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0040_auto_20200901_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlineslist',
            fields=[
                ('flag', models.IntegerField(default=0, help_text='无人船在线节点列表', primary_key=True, serialize=False)),
                ('nodelist', models.CharField(default='', help_text='在线节点', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shipp2ptest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(help_text='testname', max_length=255)),
                ('srcFilePath', models.CharField(help_text='the srcFilePath', max_length=255)),
                ('recvFilesPath', models.CharField(help_text='the recv files ', max_length=255)),
                ('testTime', models.DateTimeField(auto_now=True, help_text='the emulated time')),
            ],
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='Ship_ID',
            field=models.IntegerField(default=0, help_text='节点逻辑序号,从1开始计数', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='alt',
            field=models.FloatField(blank=True, help_text='高度5', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='heading',
            field=models.FloatField(blank=True, help_text='偏航角0', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='pitch',
            field=models.FloatField(blank=True, help_text='俯仰角1', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='poi_lat',
            field=models.FloatField(blank=True, help_text='维度3', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='poi_lng',
            field=models.FloatField(blank=True, help_text='经度4', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='roll',
            field=models.FloatField(blank=True, help_text='横滚角2', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='ve',
            field=models.FloatField(blank=True, help_text='东向速度6', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='vn',
            field=models.FloatField(blank=True, help_text='北向速度7', null=True),
        ),
        migrations.AlterField(
            model_name='ship_msg',
            name='vu',
            field=models.FloatField(blank=True, help_text='天向速度8', null=True),
        ),
    ]
